- hosts: all
  gather_facts: False
  become: yes
  vars_files:
    - ../config.yml
  pre_tasks:
    - name: Install python for Ansible
      raw: test -e /usr/bin/python || (apt -y update && apt install -y python3-minimal)
      changed_when: False
    - setup: # aka gather_facts  tasks:
  roles:
    - role: roles/apt
      tags: apt
    - role: roles/docker-ce
      tags: docker
  tasks:
    - name: Set up authorized keys for admin user
      authorized_key:
        user: root
        state: "present"
        key: "{{ lookup('file', '~/.ssh/id_rsa.pub') }}"
    - name: Set up authorized keys for vagrant user
      authorized_key:
        user: vagrant
        state: "present"
        key: "{{ lookup('file', '~/.ssh/id_rsa.pub') }}"
    # required for         
    - ansible.posix.sysctl:
        name: vm.max_map_count
        value: "{{ ansible.sysctl.vm.max_map_count }}"
        state: present
